main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Home.as_view(), name="home"),
    path('about/', views.about, name="about"),
    path('parks/', views.park_index, name='park-index'),
    path('parks/<int:park_id>/', views.park_detail, name='park-detail'),
    path('parks/create/', views.ParkCreate.as_view(), name='park-create'),
    path('parks/<int:pk>/update/', views.ParkUpdate.as_view(), name='park-update'),
    path('parks/<int:pk>/delete/', views.ParkDelete.as_view(), name='park-delete'),
    path('parks/<int:park_id>/add-log/', views.add_log, name='add-log'),
    path('accounts/signup/', views.signup, name='signup'),
    path('log/<int:pk>/update/', views.LogUpdate.as_view(), name='log-update'),
    path('log/<int:pk>/delete/', views.LogDelete.as_view(), name='log-delete'),
]

nationalparks/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


ACTIVITIES = (
        ('H', 'Hiking'),
        ('C', 'Camping'),
        ('S', 'Sight-seeing'),
        ('W', 'Swimming')
)

class Park(models.Model):
        name = models.CharField(max_length=100)
        state = models.CharField(max_length=20)
        description = models.TextField(max_length = 250)
        rating = models.IntegerField()
        user = models.ForeignKey(User, on_delete=models.CASCADE)

        def __str__(self):
                return self.name
        #redirect on successful create
        def get_absolute_url(self):
                return reverse('park-detail', kwargs={'park_id': self.id})


class Log(models.Model):
        date = models.DateField('Travelers Log')
        activity = models.CharField(
                max_length=1,
                choices = ACTIVITIES,
                default=ACTIVITIES[0][0]
                )
        
        park = models.ForeignKey(Park, on_delete=models.CASCADE)
        author = models.ForeignKey(User, on_delete=models.CASCADE)

        def __str__(self):
                return f"I went {self.get_activity_display()} on {self.date}"
        
        class Meta:
                ordering = ['-date']
        

main_app/forms.py
from django import forms
from .models import Log

class LogForm(forms.ModelForm):
    class Meta:
        model = Log
        fields = ['date', 'activity']
        widgets = {
            'date': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={
                    'placeholder': 'Select a date',
                    'type': 'date'
                }
            ),
        }

main_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Park, Log
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import LogForm
from django.contrib.auth.views import LoginView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy


#homepage
class Home(LoginView):
    template_name = 'home.html'

#about route
def about(request):
    return render(request, 'about.html')

#parks index
@login_required
def park_index(request):
    parks = Park.objects.filter(user=request.user)
    return render(request, 'parks/index.html', {'parks': parks})

#park details 
@login_required
def park_detail(request, park_id):
    park = Park.objects.get(id=park_id)
    log_form = LogForm()
    return render(request, 'parks/detail.html', {'park': park, 'log_form' : log_form})

#create cbv
class ParkCreate(LoginRequiredMixin, CreateView):
    model = Park
    fields = ['name', 'state', 'description', 'rating']
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


#update
class ParkUpdate(LoginRequiredMixin, UpdateView):
    model = Park
    fields = ['description', 'rating']


#delete
class ParkDelete(LoginRequiredMixin, DeleteView):
    model = Park
    success_url = '/parks/'

#add log
@login_required
def add_log(request, park_id):
    form = LogForm(request.POST)
    if form.is_valid():
        new_log = form.save(commit=False)
        new_log.park_id = park_id
        new_log.save()
    return redirect('park-detail', park_id=park_id)

#update log

class LogUpdate(LoginRequiredMixin, UpdateView):
    model = Log
    form_class = LogForm
    template_name = 'main_app/park_form.html'
    # success_url = '/parks/detail/'
    def get_success_url(self):
        return reverse_lazy('park-detail', kwargs= {'park_id': self.object.park.pk})
    
#delete log

class LogDelete(LoginRequiredMixin, DeleteView):
    model = Log
    def get_success_url(self):
        return reverse_lazy('park-detail', kwargs= {'park_id': self.object.park.pk})


#sign up function
def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('park-index')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %} 
{% block content %}
<h1>About Nat Park Tracker</h1>
 <h2>The handy tracker app for the wild outdoors!</h2>
<hr /> 
<p class="page-content">
 Here at GA, we're big believers in getting up and stepping away from the computer and getting some
fresh air. So with Nat Park Tracker you can step WAY WAY away from the computer! Add parks that
you've visited, notes on things you've seen, as well as you're personal ratings! Keep those Memories 
 all in one app. Oh the places you'll go!
</p>
{% endblock %}

main_app/templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <!-- <link rel="shortcut icon" type="image/png" href="" /> ADD A SHORTCUT ICON HERE. USE AI -->
    <!-- <img src="{% static 'nat_park_logo.png' %}" alt="nat park logo" />  -->
     <!-- <link rel="shortcut icon" type="image/png" href="static/images" /> -->
    <title>Nat Park Tracker</title>
    {% block head %} 
    {% endblock %}
</head>
    <body>
        <header>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li><a href="{% url 'park-index' %}">Your Parks</a></li>
                <li><a href="{% url 'park-create' %}">Add Park</a></li>
                <li>
                    <form id="logout-form" method="post" action="{% url 'logout' %}">
                        {% csrf_token %}
                    <button type="submit">Log Out</button>
                    </form>
                </li>
                {% else %}
                <li><a href='/'>Home</a></li>
                <li><a href="{% url 'about' %}">About</a></li>
                <li><a href="{% url 'signup' %}">Sign up</a></li>
                {% endif %}
            </ul>
        </nav>
        </header>
        <main>
        {% block content %} 
        {% endblock %}
        </main>
    </body>
</html>

main_app/templates/home.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link
  rel="stylesheet"
  href="{% static 'css/home.css' %}"
/>
{% endblock %} {% block content %}

<section class="logo-container">
  <div class="mtn-container">
    <img src="{% static 'images/mountain_logo.png' %}" alt="Mountain Logo" height="400px"/>
  </div>
</section>

{% if not user.is_authenticated %}
<section>
  <form action="{% url 'home' %}" method="post" class="login">
    <h1>Log in</h1>
    {% csrf_token %} {{ form.as_p }}
    <input type="hidden" name="next" value="{{ next }}" />
    <button type="submit" class="btn submit">Login</button>
  </form>
</section>
{% endif %}

{% endblock %}

main_app/templates/main_app/log_confirm_delete.html
{% extends 'base.html' %}  
{% load static %} 
{% block content %}

<div class="page-header">
  <h1>Delete Log?</h1>
</div>

<h2>Are you sure you want to delete this log?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'park-index' %}" class="btn secondary">Cancel</a>
  <button type="submit" class="btn danger">Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/park_confirm_delete.html
{% extends 'base.html' %}  
{% load static %} 
{% block content %}

<div class="page-header">
  <h1>Delete Park?</h1>
  <img src="" alt="Add an image?" />
</div>

<h2>Are you sure you want to delete {{ park.name }}?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'park-detail' park.id %}" class="btn secondary">Cancel</a>
  <button type="submit" class="btn danger">Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/park_form.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}

<div class="page-header">
  {% if park %}
    <h1>Edit {{ park.name }}</h1>
  {% else %}
  <h1>Add Park</h1>
  {% endif %}
</div>

<form action="" method="post" class="form-container">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

main_app/templates/parks/detail.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/parks/park-detail.css' %}" />
{% endblock %} 
{% block content %}
<section class="park-container">
  <div class="park-img">
  </div>
  <div class="park-details">
    <h1>{{ park.name }}</h1>
    <h2>{{ park.state }}</h2>
    <h2>Rating: {{ park.rating }}</h2>
    <p>{{ park.description }}</p>

    <div class="park-actions">
        <a href="{% url 'park-update' park.id %}" class="btn warn">Edit</a>
        <a href="{% url 'park-delete' park.id %}" class="btn danger">Delete</a>
    </div>
  </div>
</section>

<div class="log-badges-container">
  <section class="travel-log">
    <div class="subsection-title">
      </div>
      <h2>Traveler's Log</h2>
      <h3>Add a Log for {{park.name}}</h3>
        <form action="{%url 'add-log' park.id%}" method="post" class="subsection-content" autocomplete="off">
          {% csrf_token %} 
          {{ log_form.as_p }}
          <button type="submit" class="btn submit">Add Log</button>
        </form>
        <!-- ADD A REMOVE AND UPDATE BUTTON IN HERE -->
    <table>
      <thead>
        <tr>
          <th>Date</th>
          <th>Activity</th>
        </tr>
      </thead>
      <tbody>
        {% for log in park.log_set.all %}
          <tr>
            <td>{{log.date}}</td>
            <td>{{log.get_activity_display}}</td>
            <td>
              {% if log.author == user %}
              <a href="{% url 'log-update' pk=log.pk %}" class="btn submit" id="tbl-edit">Edit</a>
              <a href="{% url 'log-delete' pk=log.pk %}" class="btn danger" id="tbl-delete">X</a>
              {% endif %}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </section>
</div>
{% endblock %}

main_app/templates/parks/index.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link
  rel="stylesheet"
  href="{% static 'css/parks/park-index.css' %}"
/>
{% endblock %} {% block content %}

<section class="page-header">
  <h1>Parks List</h1>
</section>

<section class="card-container">
  {% for park in parks %}
  <div class="card">
    <a href="{% url 'park-detail' park.id %}">
    <div class="card-content">
      <div class="card-img-container">
      </div>
      <h2 class="card-title">{{ park.name }}</h2>
      <h3>{{ park.state }}</h3>
      <p>{{ park.rating }}</p>
      <p><small>{{ park.description }}</small></p>
    </div>
    </a>
  </div>
  {% endfor %}
</section>
{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}
<div class="page-header">
  <h1>Sign Up</h1>
</div>
{% if error_message %}
  <p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}